### ISSUE TITLE
请把武汉肺炎这几个敏感的字眼删除！

### ISSUE THREAD

**Issue by Amanda-Barbara** [JamestsaiTW/Taiwan-AskFaceMaskApp#1]
请把武汉肺炎这几个敏感的字眼删除！

**Comment by JamestsaiTW** [comment]
刪除與敏感的理由是? 或是可以告訴您覺得比較洽當的中文名稱以利識別嗎?

**Comment by Amanda-Barbara** [comment]
COVID-19，即是2019新型冠状病毒的缩写，

**Comment by unnhao** [comment]
> COVID-19，即是2019新型冠状病毒的缩写

勿忘本，此名称时时刻刻提醒中国人，做好卫生管控，时时注意清洁，照顾好身体，因此我认为称作武汉肺炎并没有不妥，反而我认为要称为中国武汉肺炎。况且不应该拘泥在名称，相信国家、相信党、相信政府、相信人民的力量！
